[project]
name = "matrix-portal-server"
version = "0.1.0"
description = ""
authors = [{ name = "Daniel Jones", email = "tortxof@gmail.com" }]
requires-python = "~=3.13"
readme = "README.md"
dependencies = [
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "skyfield>=1.53",
    "tzdata>=2025.2",
]
